export default [
  {
    _id: "1234",
    userID: 1,
    jobTitle: "Full Stack",
    company: "Google",
    jobStatus: "applied",
    salary: {
      minSalary: 25000,
      maxSalary: 30000,
    },
    techStack: "MERN",
    contact: "Joe Blogs",
    dataAdded: "21 Mar",
    applicationDeadline: "1 Apr",
    interviewDate: "15 Apr",
    offerDate: "1 May",
    urlLinks: "www.exmple.com",
    location: "Remote",
    jobDescription: "Working work working work",
    notes: "Make notes here",
  },
  {
    _id: "12345",
    userID: 1,
    jobTitle: "Full Stack",
    company: "FaceBook",
    jobStatus: "Watching",
    salary: {
      minSalary: 25000,
      maxSalary: 30000,
    },
    techStack: "MERN",
    contact: "Fred Blogs",
    dataAdded: "21 Mar",
    applicationDeadline: "1 Apr",
    interviewDate: "15 Apr",
    offerDate: "1 May",
    urlLinks: "www.exmple.com",
    location: "Remote",
    jobDescription: "Working work working work",
    notes: "Make notes here",
  },
  {
    _id: "123456",
    userID: 1,
    jobTitle: "Full Stack",
    company: "Netflix",
    jobStatus: "applied",
    salary: {
      minSalary: 25000,
      maxSalary: 30000,
    },
    techStack: "MERN",
    contact: "Brian Blogs",
    dataAdded: "21 Mar",
    applicationDeadline: "1 Apr",
    interviewDate: "15 Apr",
    offerDate: "1 May",
    urlLinks: "www.exmple.com",
    location: "Remote",
    jobDescription: "Working work working work",
    notes: "Make notes here",
  },
  {
    _id: "1234567",
    userID: 1,
    jobTitle: "Backend",
    company: "Apple",
    jobStatus: "applied",
    salary: {
      minSalary: 25000,
      maxSalary: 30000,
    },
    techStack: "MERN",
    contact: "Rita Blogs",
    dataAdded: "21 Mar",
    applicationDeadline: "1 Apr",
    interviewDate: "15 Apr",
    offerDate: "1 May",
    urlLinks: "www.exmple.com",
    location: "Remote",
    jobDescription: "Working work working work",
    notes: "Make notes here",
  },
  {
    _id: "1234678",
    userID: 1,
    jobTitle: "Dev Ops",
    company: "Microsoft",
    jobStatus: "applied",
    salary: {
      minSalary: 25000,
      maxSalary: 30000,
    },
    techStack: "MERN",
    contact: "Joe Blogs",
    dataAdded: "21 Mar",
    applicationDeadline: "1 Apr",
    interviewDate: "15 Apr",
    offerDate: "1 May",
    urlLinks: "www.exmple.com",
    location: "Remote",
    jobDescription: "Working work working work",
    notes: "Make notes here",
  },
];
